### ISSUE TITLE
Wiki pages: Expander Agent Tools wiki pages require update

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/Translator-All#10]
Hi @saramsey , @dkoslicki, @edeutsch. Would you be the best contacts to ask about the [wiki pages](https://github.com/NCATSTranslator/Translator-All/wiki) updates? 

I have these pages for expander agent tools that are blank and need to be updated for the spring relays:   

https://github.com/NCATSTranslator/Translator-All/wiki/ARAX
https://github.com/NCATSTranslator/Translator-All/wiki/KG2

Please update these pages using the template structure provided on the page.

**Comment by saramsey** [comment]
Hi @tursynay thanks for bringing this to my attention. Yes, the three of us that are assigned (me, @edeutsch  and @dkoslicki ) are the right people to address this.  I am almost done with the KG2 wiki page. We'll get the ARAX page done before the relay.

**Comment by dkoslicki** [comment]
The wiki has been updated (save for use case examples, which will be populated shortly). See: https://github.com/RTXteam/RTX/issues/1417

**Comment by tursynay** [comment]
Thank you, @dkoslicki . Much appreciated

**Comment by saramsey** [comment]
Update: we have added an example python script for the KG2 KP API, and that script is linked on the KG2 wiki page:  https://github.com/NCATSTranslator/Translator-All/wiki/KG2
