### ISSUE TITLE
Wiki pages:

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/Translator-All#11]
Hi @newgene, @andrewsu, @kevinxin90, I am contacting teams regarding the wiki pages we have for the tools and teams. Would you be the best contact for the BioThings Explorer (BTE) and Pathway Figure OCR (PFOCR) tools? 

We need these two pages updated with details specified in the templates [here](https://github.com/NCATSTranslator/Translator-All/wiki)

https://github.com/NCATSTranslator/Translator-All/wiki/BioThings-Explorer-(BTE)
https://github.com/NCATSTranslator/Translator-All/wiki/Pathway-Figure-OCR-(PFOCR)

Please update these pages before the spring relay.

**Comment by andrewsu** [comment]
information added, thanks!
