### ISSUE TITLE
Wiki Pages: Ranking Agent pages require updates

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/Translator-All#13]
Hi Patrick, I only have you for the Ranking agent as a contact so forgive me for sending all of these to you. Is there anyone else on Ranking agent that can take on some of the page updates? We need these tool and team pages to be updates before the spring relays:

https://github.com/NCATSTranslator/Translator-All/wiki/Ranking-Agent 
https://github.com/NCATSTranslator/Translator-All/wiki/ARAGORN 
https://github.com/NCATSTranslator/Translator-All/wiki/Automat 
https://github.com/NCATSTranslator/Translator-All/wiki/Strider
https://github.com/NCATSTranslator/Translator-All/wiki/Ranker
https://github.com/NCATSTranslator/Translator-All/wiki/Answer-Coalescence

**Comment by mmersmann** [comment]
@tursynay This is being handled internally by the Ranking Agent team. Closing this issue.
