### ISSUE TITLE
Wiki Pages: Exposures Provider pages require updates

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/Translator-All#15]
Hi Kara,

I am reviewing the wiki pages and asking teams update their pages. We have a new template for what we need for the teams and tools pages here: https://github.com/NCATSTranslator/Translator-All/wiki 

I have three pages for Exposures Provider to update, I am not sure who I should ask besides you on the team. Please let me know:

https://github.com/NCATSTranslator/Translator-All/wiki/Exposures-Provider
https://github.com/NCATSTranslator/Translator-All/wiki/CAM-KP
https://github.com/NCATSTranslator/Translator-All/wiki/ICEES--Exposure-Provider

**Comment by mmersmann** [comment]
@tursynay This is being handled internally by the Exposures Provider team. Closing this issue.
