### ISSUE TITLE
Wiki pages: Clinical Data Provider page is blank, need details

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/Translator-All#2]
In an effort to have a single source robust information source for Translator tools, we are attempting to update the wiki pages with team, KP, ARA, ARS, SRI tool information. Clinical Data Provider page is blank. @NCATSTranslator/clinical-data-services-provider, please provide more details on this page.

**Comment by tursynay** [comment]
Hi @vemonet, we have recently updated documentation and template structure for Translator tools, services and teams in the wikis [here](https://github.com/NCATSTranslator/Translator-All/wiki) which now includes minimum requirements for Translator Tools Documentation from the Program Milestones for 2021. Would you be able to take a look at the Clinical Data Provider tools in this list [here](https://github.com/NCATSTranslator/Translator-All/wiki) and add/update the information as specified in the page. We also need the Clinical Data Provider team wiki page reviewed and updated, please. Here is the [team page.](https://github.com/NCATSTranslator/Translator-All/wiki/Clinical-Data-Provider) Please let me know if you are not the person who I should be contacting about this. Thanks.

**Comment by vemonet** [comment]
Hi @tursynay thanks for the notification I did not noticed the Wiki pages changed

When we originally started it, we created a wiki page for all existing teams at the time, so most teams already have a page created. In our case we have this one: https://github.com/NCATSTranslator/Translator-All/wiki/Clinical-Data-Services-Provider 

The links to those existing pages can be found in the Wiki **Pages (31)** menu on the right, we might want to be careful to avoid too many duplicates that would make the wiki confusing and hard to navigate

We are already using a good part of the required template, we will update with missing requirements asap 

I just have a question:
> Guide for user on how to open an issue and find current issues to avoid duplicate issues
> How to build your own instance for NCATS Deployment pipeline

In our case all processes related to our tool are documented in the `README.md`, `CONTRIBUTING.md`, or `TEST.md` files

Is it possible to provide links to those documents in the wiki? So we avoid duplicating documentations

**Comment by tursynay** [comment]
Hi @vemonet, thank you for updating the team page with additional requirements. Yes, absolutely agree, we don't want any duplicate pages. What I meant was to have 1 team page and however many tool pages (one per tool) with details outlined in the documentation requirements template, with these tool pages hyperlinked to the team page and the home page in the Tools & Services list. 

wrt: In our case all processes related to our tool are documented in the README.md, CONTRIBUTING.md, or TEST.md files. 
Is it possible to provide links to those documents in the wiki? So we avoid duplicating documentations. 

That is fine, please provide a link or short sentence that such technical documentation can be found in the .md files in the designated repo. 

These all should help teams/users find what they are looking for as Translator operates on many github orgs and it is cumbersome to find things sometimes.

Thank you.

**Comment by vemonet** [comment]
Hi @tursynay 

We updated the wiki pages for the Clinical Data provider team: https://github.com/NCATSTranslator/Translator-All/wiki/Clinical-Data-Provider

We created a page for each tool (following the KP template, we also added the contact for each tool), the KP pages have been put in a `Clinical-Data-Providers` folder in the wiki, they are all referenced in the Wiki index page and the Clinical Data Provider page

We just need to complete the tools pages by adding Technical guides and Use-cases (we will develop and document them asap)

Let us know if their are anything wrong, apart from the missing guides and use-cases

And thanks a lot for helping to make the Translator tools more accessible!

**Comment by tursynay** [comment]
Thank you for the update @vemonet, I saw the pages, it looks really nice! I look forward to others and will use your pages as examples for others

**Comment by tursynay** [comment]
Thank you @vemonet, closing this issue.
