### ISSUE TITLE
Wiki pages: Genetics Knowledge Provider page needs additional information

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/Translator-All#3]
Hi @NCATSTranslator/genetics-provider team. In an effort to have a single source robust information source for Translator tools, we are attempting to update the wiki pages with team, KP, ARA, ARS, SRI tool information. Wiki page for Genetics provider needs details for:

- Team Contact
- Knowledge Source 
- Source Code

Please update the wiki page with the missing information. Here is the link to the wiki page: https://github.com/NCATSTranslator/Translator-All/wiki/Genetics-Knowledge-Provider

**Comment by tursynay** [comment]
Hi @vdancik, 

We have recently updated documentation and template structure for Translator tools, services and teams in the wikis [here](https://github.com/NCATSTranslator/Translator-All/wiki/Genetics-Knowledge-Provider) which now includes minimum requirements for Translator Tools Documentation from the Program Milestones for 2021. 

Would you be able to take a look at the Genetics Data Provider tools in this list [here](https://github.com/NCATSTranslator/Translator-All/wiki) and add/update the information as specified in the page. 

We also need the Genetics Data Provider team wiki page reviewed and updated, please. [Here ](https://github.com/NCATSTranslator/Translator-All/wiki/Genetics-Knowledge-Provider)is the team page. Please let me know if you are not the person who I should be contacting about this. The Team and Tool templates should be used to update the info. 

Thanks.

**Comment by tursynay** [comment]
Hi @marcdubybroad, I contacted Vlado regarding this and Vlado told me that you would be the best person to contact. 

We have recently updated documentation and template structure for Translator tools, services and teams in the wikis [here](https://github.com/NCATSTranslator/Translator-All/wiki/Genetics-Knowledge-Provider) which now includes minimum requirements for Translator Tools Documentation from the Program Milestones for 2021. 

Would you be able to take a look at the Genetics Data Provider tools in this list [here](https://github.com/NCATSTranslator/Translator-All/wiki) and add/update the information as specified in the page. 

We also need the Genetics Data Provider team wiki page reviewed and updated, please. [Here ](https://github.com/NCATSTranslator/Translator-All/wiki/Genetics-Knowledge-Provider)is the team page. Please let me know if you are not the person who I should be contacting about this. The Team and Tool templates should be used to update the info. 

Thank you.

**Comment by tursynay** [comment]
Hi Marc, I am following up with teams about their pages. Any updates on these pages? If you are unable to update these pages, please recommend someone who could help.

**Comment by marcdubybroad** [comment]
The page has been updated with our latest information.

**Comment by tursynay** [comment]
Thank you, Marc.
