### ISSUE TITLE
Wiki pages: Service Provider page update

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/Translator-All#5]
Hi @NCATSTranslator/service-provider team. In an effort to have a single source robust information source for Translator tools, we are attempting to update the wiki pages with team, KP, ARA, ARS, SRI tool information. Wiki page for Service Provider needs details for:

- Team Contact

Please update the wiki page with the missing information. Here is the link to the wiki page: 
https://github.com/NCATSTranslator/Translator-All/wiki/Service-Provider

**Comment by newgene** [comment]
added.

**Comment by tursynay** [comment]
Hi @newgene, 

Sorry for jumping the gun with this issue. We have recently updated documentation and template structure for Translator tools, services and teams in the wikis [here](https://github.com/NCATSTranslator/Translator-All/wiki) which now includes minimum requirements for Translator Tools Documentation from the Program Milestones for 2021. 

Would you be able to take a look at the Service Provider tools in this list [here](https://github.com/NCATSTranslator/Translator-All/wiki) and add/update the information as specified in the page and in the templates. We also need the Service Provider team wiki page reviewed and updated as in the teams template [here](https://github.com/NCATSTranslator/Translator-All/wiki/Team-Introduction-Template), please. Here is the Service Provider [team page](https://github.com/NCATSTranslator/Translator-All/wiki/Service-Provider). 

Please let me know if you are not the person who I should be contacting about this. Thanks.

**Comment by newgene** [comment]
I updated the Service Provider tool list on [this overall wiki page](https://github.com/NCATSTranslator/Translator-All/wiki).

Will still need to update the Service Provider [team page](https://github.com/NCATSTranslator/Translator-All/wiki/Service-Provider).

**Comment by tursynay** [comment]
Hi @newgene , 
any updates on this issue> As we are getting closer to the relays I am following up with teams on their tools and teams pages:
I see these for the Service Provider team, please check the wikis:

- BioThings SDK
- MyChem.info
- MyDisease.info
- MyGene.info
- MyVariant.info
- Other hosted BioThings KPs
- SmartAPI

**Comment by newgene** [comment]
updated the [Service Provider team page](https://github.com/NCATSTranslator/Translator-All/wiki/Service-Provider).
