### ISSUE TITLE
Wiki pages: Explanatory Agent page needs an update

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/Translator-All#6]
Hi @NCATSTranslator/explanatory-agent team. In an effort to have a single source robust information source for Translator tools, we are attempting to update the wiki pages with team, KP, ARA, ARS, SRI tool information. Wiki page for Explanatory agent needs details for:

External Documentation

Please update the wiki page with the missing information. Here is the link to the wiki page: 
https://github.com/NCATSTranslator/Translator-All/wiki/Explanatory-Agent

**Comment by Rosinaweber** [comment]
Hi Tursynay:
Have guidelines for documentation been agreed upon? If yes, could you please show us where to find them?
Thanks,
Rosina-

**Comment by tursynay** [comment]
Hi @Rosinaweber,

Sorry for jumping the gun with this issue. We have recently updated documentation and template structure for Translator tools, services and teams in the wikis [here](https://github.com/NCATSTranslator/Translator-All/wiki) which now includes minimum requirements for Translator Tools Documentation from the Program Milestones for 2021.

Would you be able to take a look at the Explanatory Agent tools in this list [here](https://github.com/NCATSTranslator/Translator-All/wiki) and add/update the information as specified in the page and in the templates. We also need the Explanatory Agent team[ wiki (https://github.com/NCATSTranslator/Translator-All/wiki/Explanatory-Agent) page reviewed and updated as in the teams template here, please. 

Please let me know if you are not the person who I should be contacting about this. Thanks.

**Comment by Rosinaweber** [comment]
Hi @tursynay 
Thanks for sending the link with the instructions. Yes, I am the right person, and this is in our to-do list for the May deadline.
Rosina-

**Comment by tursynay** [comment]
@Rosinaweber, hi :)

I am following up with folks as we are getting close to the relays and wanted to have this ticket resurface for everyone.

Thank you and please let me know if I can provide any more information for this.

**Comment by Rosinaweber** [comment]
Dear Tursynay:

We are working on our documentation. Please note that we only joined the project last year and until this January were not able to leverage our implementation given the small number of KPs that were TRAPI compliant. We restarted the implementation design in February and are still implementing our agent to be able to respond to multiple queries.

Thank you for the reminder. We appreciate it.
Rosina-

**Comment by tursynay** [comment]
Thanks for the update, Rosina.

Tursynay
