### ISSUE TITLE
Wiki pages: ARS team page needs an update

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/Translator-All#8]
Hi Sarah,
would you update the ARS page? https://github.com/NCATSTranslator/Translator-All/wiki/Autonomous-Relay-System-(ARS) 

Is the description complete?
Team contact is needed
Should it list the ARAs that ARS access to date?
 
I am not sure what is missed, but it is a good time to review.

**Comment by tursynay** [comment]
@MarkDWilliams and @sstemann, wanted to follow up on this. Would you be able to update this page?

**Comment by sstemann** [comment]
over to you @tursynay is this better?  should i like to the specific tool pages or is it apparent they can use the right hand bookmark thing?

**Comment by tursynay** [comment]
Thanks, @sstemann. Looks good, I see that Vincent included more to the page. Is that what you asked for to add?

**Comment by tursynay** [comment]
Thanks, Sarah. closing this issue
