### ISSUE TITLE
Wiki pages: SRI page needs to be updated

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/Translator-All#9]
Hi @patrickkwang  

Working through the wiki pages and looks like SRI wiki is pretty bare. Would you be able to add details to it? if not you, should it be Chris B? https://github.com/NCATSTranslator/Translator-All/wiki/Standards-and-Reference-Implementation-(SRI) 

On this home page of the wiki, we have listed the SRI tools as Utilities. Should they be listed under SRI? https://github.com/NCATSTranslator/Translator-All/wiki 

Thanks

**Comment by patrickkwang** [comment]
This looks pretty good to me. Are there specific details that we're missing?

**Comment by tursynay** [comment]
Looks good but the description seems bare, no?
